# Generated by Django 3.2.12 on 2022-05-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expire_date',
            field=models.DateField(null=True),
        ),
    ]
