# Generated by Django 3.2.12 on 2022-05-24 18:42

from django.db import migrations
from django.utils import timezone


def assign_expire_dates(apps, schema_editor):
    Profile = apps.get_model('Profile', 'Profile')
    delta = timezone.timedelta(days=365)
    for p in Profile.objects.all():
        p.expire_date = timezone.now().date() + delta
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_add_expire_date'),
    ]

    operations = [
        migrations.RunPython(assign_expire_dates)
    ]
